export default [
  { value: "Etc/GMT-12", label: "Etc/GMT-12", offset: -720 },
  { value: "Etc/GMT-11", label: "Etc/GMT-11", offset: -660 },
  { value: "Pacific/Midway", label: "Pacific/Midway", offset: -660 },
  { value: "America/Adak", label: "America/Adak", offset: -600 },
  { value: "America/Anchorage", label: "America/Anchorage", offset: -540 },
  { value: "Pacific/Gambier", label: "Pacific/Gambier", offset: -540 },
  {
    value: "America/Dawson_Creek",
    label: "America/Dawson_Creek",
    offset: -480
  },
  { value: "America/Ensenada", label: "America/Ensenada", offset: -480 },
  { value: "America/Los_Angeles", label: "America/Los_Angeles", offset: -480 },
  { value: "America/Chihuahua", label: "America/Chihuahua", offset: -420 },
  { value: "America/Denver", label: "America/Denver", offset: -420 },
  { value: "America/Belize", label: "America/Belize", offset: -360 },
  { value: "America/Cancun", label: "America/Cancun", offset: -360 },
  { value: "America/Chicago", label: "America/Chicago", offset: -360 },
  { value: "Chile/EasterIsland", label: "Chile/EasterIsland", offset: -360 },
  { value: "America/Bogota", label: "America/Bogota", offset: -300 },
  { value: "America/Havana", label: "America/Havana", offset: -300 },
  { value: "America/New_York", label: "America/New_York", offset: -300 },
  { value: "America/Caracas", label: "America/Caracas", offset: -240 },
  {
    value: "America/Campo_Grande",
    label: "America/Campo_Grande",
    offset: -240
  },
  { value: "America/Glace_Bay", label: "America/Glace_Bay", offset: -240 },
  { value: "America/Goose_Bay", label: "America/Goose_Bay", offset: -240 },
  { value: "America/Santiago", label: "America/Santiago", offset: -240 },
  { value: "America/La_Paz", label: "America/La_Paz", offset: -240 },
  {
    value: "America/Argentina/Buenos_Aires",
    label: "America/Argentina/Buenos_Aires",
    offset: -180
  },
  { value: "America/Montevideo", label: "America/Montevideo", offset: -180 },
  { value: "America/Araguaina", label: "America/Araguaina", offset: -180 },
  { value: "America/Godthab", label: "America/Godthab", offset: -180 },
  { value: "America/Miquelon", label: "America/Miquelon", offset: -180 },
  { value: "America/Sao_Paulo", label: "America/Sao_Paulo", offset: -180 },
  { value: "America/St_Johns", label: "America/St_Johns", offset: -180 },
  { value: "America/Noronha", label: "America/Noronha", offset: -120 },
  { value: "Atlantic/Cape_Verde", label: "Atlantic/Cape_Verde", offset: -60 },
  { value: "Europe/Belfast", label: "Europe/Belfast", offset: 0 },
  { value: "Africa/Abidjan", label: "Africa/Abidjan", offset: 0 },
  { value: "Europe/Dublin", label: "Europe/Dublin", offset: 0 },
  { value: "Europe/Lisbon", label: "Europe/Lisbon", offset: 0 },
  { value: "Europe/London", label: "Europe/London", offset: 0 },
  { value: "UTC", label: "UTC", offset: 0 },
  { value: "Africa/Algiers", label: "Africa/Algiers", offset: 60 },
  { value: "Africa/Windhoek", label: "Africa/Windhoek", offset: 60 },
  { value: "Atlantic/Azores", label: "Atlantic/Azores", offset: 60 },
  { value: "Atlantic/Stanley", label: "Atlantic/Stanley", offset: 60 },
  { value: "Europe/Amsterdam", label: "Europe/Amsterdam", offset: 60 },
  { value: "Europe/Belgrade", label: "Europe/Belgrade", offset: 60 },
  { value: "Europe/Brussels", label: "Europe/Brussels", offset: 60 },
  { value: "Africa/Cairo", label: "Africa/Cairo", offset: 120 },
  { value: "Africa/Blantyre", label: "Africa/Blantyre", offset: 120 },
  { value: "Asia/Beirut", label: "Asia/Beirut", offset: 120 },
  { value: "Asia/Damascus", label: "Asia/Damascus", offset: 120 },
  { value: "Asia/Gaza", label: "Asia/Gaza", offset: 120 },
  { value: "Asia/Jerusalem", label: "Asia/Jerusalem", offset: 120 },
  { value: "Africa/Addis_Ababa", label: "Africa/Addis_Ababa", offset: 180 },
  { value: "Asia/Riyadh89", label: "Asia/Riyadh89", offset: 180 },
  { value: "Europe/Minsk", label: "Europe/Minsk", offset: 180 },
  { value: "Asia/Tehran", label: "Asia/Tehran", offset: 180 },
  { value: "Asia/Dubai", label: "Asia/Dubai", offset: 240 },
  { value: "Asia/Yerevan", label: "Asia/Yerevan", offset: 240 },
  { value: "Europe/Moscow", label: "Europe/Moscow", offset: 240 },
  { value: "Asia/Kabul", label: "Asia/Kabul", offset: 240 },
  { value: "Asia/Tashkent", label: "Asia/Tashkent", offset: 300 },
  { value: "Asia/Kolkata", label: "Asia/Kolkata", offset: 300 },
  { value: "Asia/Katmandu", label: "Asia/Katmandu", offset: 300 },
  { value: "Asia/Dhaka", label: "Asia/Dhaka", offset: 360 },
  { value: "Asia/Yekaterinburg", label: "Asia/Yekaterinburg", offset: 360 },
  { value: "Asia/Rangoon", label: "Asia/Rangoon", offset: 360 },
  { value: "Asia/Bangkok", label: "Asia/Bangkok", offset: 420 },
  { value: "Asia/Novosibirsk", label: "Asia/Novosibirsk", offset: 420 },
  { value: "Etc/GMT+8", label: "Etc/GMT+8", offset: 480 },
  { value: "Asia/Hong_Kong", label: "Asia/Hong_Kong", offset: 480 },
  { value: "Asia/Krasnoyarsk", label: "Asia/Krasnoyarsk", offset: 480 },
  { value: "Australia/Perth", label: "Australia/Perth", offset: 480 },
  { value: "Australia/Eucla", label: "Australia/Eucla", offset: 480 },
  { value: "Asia/Irkutsk", label: "Asia/Irkutsk", offset: 540 },
  { value: "Asia/Seoul", label: "Asia/Seoul", offset: 540 },
  { value: "Asia/Tokyo", label: "Asia/Tokyo", offset: 540 },
  { value: "Australia/Adelaide", label: "Australia/Adelaide", offset: 540 },
  { value: "Australia/Darwin", label: "Australia/Darwin", offset: 540 },
  { value: "Pacific/Marquesas", label: "Pacific/Marquesas", offset: 540 },
  { value: "Etc/GMT+10", label: "Etc/GMT+10", offset: 600 },
  { value: "Australia/Brisbane", label: "Australia/Brisbane", offset: 600 },
  { value: "Australia/Hobart", label: "Australia/Hobart", offset: 600 },
  { value: "Asia/Yakutsk", label: "Asia/Yakutsk", offset: 600 },
  { value: "Australia/Lord_Howe", label: "Australia/Lord_Howe", offset: 600 },
  { value: "Asia/Vladivostok", label: "Asia/Vladivostok", offset: 660 },
  { value: "Pacific/Norfolk", label: "Pacific/Norfolk", offset: 660 },
  { value: "Etc/GMT+12", label: "Etc/GMT+12", offset: 720 },
  { value: "Asia/Anadyr", label: "Asia/Anadyr", offset: 720 },
  { value: "Asia/Magadan", label: "Asia/Magadan", offset: 720 },
  { value: "Pacific/Auckland", label: "Pacific/Auckland", offset: 720 },
  { value: "Pacific/Chatham", label: "Pacific/Chatham", offset: 720 },
  { value: "Pacific/Tongatapu", label: "Pacific/Tongatapu", offset: 780 },
  { value: "Pacific/Kiritimati", label: "Pacific/Kiritimati", offset: 840 }
];
